### ISSUE TITLE
wheels break localshop

### ISSUE THREAD

**Issue by fly** [mvantellingen/localshop#138]
from localshop log:
```
ERROR 2015-04-23 19:59:36,099 base 10245 140388478600960 Internal Server Error: /packages/a_pkg/download/6920/a_pkg-1.5.0.tar.gz
Traceback (most recent call last):
  File "/opt/virtualenvs/localshop/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/virtualenvs/localshop/local/lib/python2.7/site-packages/localshop/apps/permissions/utils.py", line 61, in decorator
    return view_func(request, *args, **kwargs)
  File "/opt/virtualenvs/localshop/local/lib/python2.7/site-packages/localshop/apps/packages/views.py", line 159, in download_file
    release_file = models.ReleaseFile.objects.get(pk=pk)
  File "/opt/virtualenvs/localshop/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/virtualenvs/localshop/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: ReleaseFile matching query does not exist.
```

`pip install a_pkg` output:
```
Collecting a_pkg
  HTTP error 500 while getting https://pypi/packages/a_pkg/download/6920/a_pkg-1.5.0.tar.gz#md5=d5556c6e1dd9c1df2b3d59acb90278f1 (from https://pypi/simple/a_pkg/)
  Could not install requirement a_pkg from https://pypi/packages/a_pkg/download/6920/a_pkg-1.5.0.tar.gz#md5=d5556c6e1dd9c1df2b3d59acb90278f1 because of error 500 Server Error: INTERNAL SERVER ERROR
  Could not install requirement a_pkg from https://pypi/packages/a_pkg/download/6920/a_pkg-1.5.0.tar.gz#md5=d5556c6e1dd9c1df2b3d59acb90278f1 because of HTTP error 500 Server Error: INTERNAL SERVER ERROR for URL https://pypi/packages/a_pkg/download/6920/a_pkg-1.5.0.tar.gz#md5=d5556c6e1dd9c1df2b3d59acb90278f1 (from https://pypi/simple/a_pkg/)
```

So it looks like pip asks localshop for releases, and localshop sees the release but tries to serve an sdist that doesn't exist?

**Comment by canassa** [comment]
I've testes uploading/download wheels and it seems to be working fine.

Could you please provide more detailed steps on how to reproduce this error?

Thanks
