### ISSUE TITLE
pip search fails with 404

### ISSUE THREAD

**Issue by sposs** [mvantellingen/localshop#139]
Hi,
Even on projects that are there, the search fails with
```
HTTP error 404 while getting http://user:pass@myhost:7000/simple/
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 246, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 786, in request
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: NOT FOUND
```
I did
```
pip search  --index http://user:pass@myhost:7000/simple/ pyzmq
```

Also, is it possible to allow anonymous search, i.e. not having to specify the password?

**Comment by canassa** [comment]
Hi,

I think that the correct search endpoint on Localshop is `http://user:pass@yourserver/RPC2`.

The only problem is that this part of the code is not very well tested :cry: I just tested sending a `pip search` to Localshop and it raised an 500 error. I will look into it.

**Comment by canassa** [comment]
Please, update to 0.8.2 and restest
