### ISSUE TITLE
ImportError: Could not import settings 'localshop.settings'

### ISSUE THREAD

**Issue by yytj17** [mvantellingen/localshop#172]
Could you please help me with this:

C:\Users\Administrator>localshop
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\localshop.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\localshop\runner.py", line 12, in main
    execute_from_command_line(sys.argv)
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "c:\python27\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 46, in __getattr__
    self._setup(name)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "c:\python27\lib\site-packages\django\conf\__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'localshop.settings' (Is it on sys.path? Is there an import error in the settings file?): cannot import name _uuid_generate_random

**Comment by yytj17** [comment]
I follow the installing docs and the second step is "localshop init", then this Error happens.

**Comment by canassa** [comment]
Thanks for the report. Could you post the output of `python --version`?

**Comment by yytj17** [comment]
Oh, I've got the solution from google:
http://stackoverflow.com/questions/34198538/cannot-import-name-uuid-generate-random-in-heroku-django

It's module "kombu(3.0.24)". When I update it to latest(3.0.33), the issue doesn't exist anymore.
Thanks.

**Comment by yytj17** [comment]
BTW, the version of python is 2.7.11.

**Comment by morganthrapp** [comment]
Can this be reopened? I can confirm this still happens.

Steps to reproduce:

1. Create virtual environment with Python 3.5.1 on Windows 10.

2. Run `pip install localshop`.

3. Run `localshop init`.

**Comment by gangh** [comment]
this error still happens when i follow the installing docs.
And this operation solved this error:
```
pip install -r reqirements.txt
```
try this
(with python 3.5)
There are mistakes in setup install requires.

**Comment by mpounsett** [comment]
This is still a problem with python 3.6.5 and 2.7.15.  If I install `kombu==3.0.30` then the `localshop.settings` error goes away, but moves to something else.  

python 3.6.5: `AttributeError: module 'html.parser' has no attribute 'HTMLParseError'`
python 2.7.15: `django.core.exceptions.ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named _sqlite3`
